declare function getApp()
declare function onHasAbility(a:boolean)
declare function onPageShow(a:string)
declare function onPageUnload(a:string)
declare function onPageReady(a:string)
declare function onComponentUpdate({ data: any, path: string })
declare function onComponentReady(a:string)
declare function onXfetchRequest(a:string)
declare function onXfetchResponse(a:string)
declare let expect
